version: '3'
services:
  postgres:
    container_name: database
    image: postgres:15.1-alpine
    ports:
      - "${BOOKSTORE_DATABASE_LOCAL_PORT}:${BOOKSTORE_DATABASE_DOCKER_PORT}/"
    environment:
        - POSTGRES_USER=${BOOKSTORE_DATABASE_USERNAME}
        - POSTGRES_PASSWORD=${BOOKSTORE_DATABASE_PASSWORD}
        - POSTGRES_DB=${BOOKSTORE_DATABASE_NAME}
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${BOOKSTORE_DATABASE_LOCAL_PORT}/${BOOKSTORE_DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${BOOKSTORE_DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${BOOKSTORE_DATABASE_PASSWORD}

